version: "3"
services:
  brat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BRAT_USERNAME=${BRAT_USERNAME}
        - BRAT_PASSWORD=${BRAT_PASSWORD}
        - BRAT_EMAIL=${BRAT_EMAIL}
    container_name: brat_covox
    restart: unless-stopped
    ports:
     - "8005:80"
    volumes:
     - ./data/brat-data:/var/www/brat/data
     - ./data/config.py:/var/www/brat/config.py