services:

  brat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BRAT_USERNAME=covox_user
        - BRAT_PASSWORD=brat_covox2021
        - BRAT_EMAIL=brat@example.com
    container_name: brat_covox
    restart: unless-stopped
    ports:
     - "8005:80"
    volumes:
     - ./data/brat-data:/var/www/brat/brat-1.3_Crunchy_Frog/data
     - ./data/config.py:/var/www/brat/brat-1.3_Crunchy_Frog/config.py